# Local development Dockerfile (no SSL)
FROM node:21.7.3-alpine3.19 as build

WORKDIR /app
COPY . .
RUN npm ci --force
RUN npm run build

FROM nginx:alpine
COPY nginx.local.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist/browser /usr/share/nginx/html
COPY docker-entrypoint.sh /docker-entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["nginx", "-g", "daemon off;"]
