# the events block is required
events{}

http {
    # include the default mime.types to map file extensions to MIME types
    include /etc/nginx/mime.types;

    map  $ssl_client_s_dn  $ssl_client_s_dn_cn {
	default "";
	~CN=(?<CN>[^.]+) $CN;
    }
    server {
        listen 80;
        server_name doctor-osteopat:80.kz;

        root /usr/share/nginx/about;

        index index.html;

	location / {
            # try to serve the requested URI. if that fails then try to
            # serve the URI with a trailing slash. if that fails, then
            # serve the index.html file; this is needed in order to serve
            # Angular routes--e.g.,'localhost:8080/customer' will serve
            # the index.html file
            try_files $uri $uri/ /index.html;
        }

    }
    server {
	listen 			443 ssl;
	server_name		doctor-osteopat.kz;

	ssl_certificate 	/etc/ssl/server/back.crt;
	ssl_certificate_key 	/etc/ssl/server/back.key;
	ssl_client_certificate	/etc/ssl/server/ca.crt;
	ssl_verify_client 	on;

        # set the root directory for the server (we need to copy our
        # application files here)
        root /usr/share/nginx/html;

        # set the default index file for the server (Angular generates the
        # index.html file for us and it will be in the above directory)
        index index.html;
	location /n8n/ {
	    resolver 127.0.0.11 ipv6=off;
    	    proxy_pass http://n8n:5678$request_uri;

	    proxy_http_version 1.1;

	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection 'upgrade';
	    proxy_set_header Host $host;
	    proxy_cache_bypass $http_upgrade;

	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_set_header X-Forwarded-Host $host;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Port $server_port;

	    proxy_redirect off;
        }

	location /n8nassets/ {
	    resolver 127.0.0.11 ipv6=off;
    	    proxy_pass http://n8n:5678/n8n$request_uri;

	    proxy_http_version 1.1;

	    proxy_set_header Upgrade $http_upgrade;
	    proxy_set_header Connection 'upgrade';
	    proxy_set_header Host $host;
	    proxy_cache_bypass $http_upgrade;

	    proxy_set_header X-Forwarded-Proto $scheme;
	    proxy_set_header X-Forwarded-Host $host;
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	    proxy_set_header X-Forwarded-Port $server_port;

	    proxy_redirect off;
        }

	location /api/ {
	    resolver 127.0.0.11 ipv6=off;
	    proxy_pass http://back/$ssl_client_s_dn_cn$request_uri;
	}
	location /dbeaver/ {
	    resolver 127.0.0.11 ipv6=off;
	    proxy_pass http://dbeaver:8978;
	}
	location /pg/ {
	    resolver 127.0.0.11 ipv6=off;
	    proxy_pass http://pgadmin;

	    proxy_set_header X-Script-Name /pg;
	    proxy_set_header Host $host;
	    proxy_set_header X-Real-IP $remote_addr;
	}
	# location /h2-console {
	#    resolver 127.0.0.11 ipv6=off;
	#    proxy_pass http://back-h2/h2-console;
	#}

        # specify the configuration for the '/' location
        location / {
            if ($ssl_client_verify != SUCCESS) {
		return 401;
	    }

            # try to serve the requested URI. if that fails then try to
            # serve the URI with a trailing slash. if that fails, then
            # serve the index.html file; this is needed in order to serve
            # Angular routes--e.g.,'localhost:8080/customer' will serve
            # the index.html file
            try_files $uri $uri/ /index.html;
            
        }

        auth_basic "Restricted Content";
        auth_basic_user_file /etc/nginx/.htpasswd;

    }
}

